clear all;
close all;

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS=0
wrapped("sample0.jpg");
pause(0.5)
clear all;
close all;
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS=1
wrapped("sample1.jpg");
pause(0.5)
clear all;
close all;
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS=2
wrapped("sample2.jpg");
pause(0.5)
clear all;
close all;
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS=3
wrapped("sample3.jpg");
pause(0.5)
clear all;
close all;
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS=4
wrapped("sample4.jpg");
pause(0.5)
clear all;
close all;
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS=0
wrapped("sample5.jpg");
pause(0.5)
clear all;
close all;
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS=6
wrapped("sample6.jpg");
pause(0.5)
clear all;
close all;
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS=7
wrapped("sample7.jpg");
pause(0.5)
clear all;
close all;
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS=8
wrapped("sample8.jpg");
pause(0.5)
clear all;
close all;
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS=9
wrapped("sample9.jpg");
